# Generated by Django 5.2.6 on 2025-11-13 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_flexibility', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Flexibilité sur les prix')),
                ('rfx_deadline_compliance', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Respect des délais (Réponse au RFX)')),
                ('advisory_capability', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name="Capacité à conseiller (nouveau produit, dans l'exécution de projet)")),
                ('relationship_quality', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Contact relationnel (Réactivité des interlocuteurs)')),
                ('rfx_response_quality', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Qualité des réponses aux RFx (eSourcing, Mail)')),
                ('credit_policy', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Politique de crédit (exigence vis-à-vis des acomptes)')),
                ('buyer_final_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moyenne des 6 critères (calculée automatiquement)', max_digits=4, verbose_name='Note finale acheteur')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Évaluation acheteur',
                'verbose_name_plural': 'Évaluations acheteur',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_compliance', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Delivery Compliance to Order (Quantity & Quality)')),
                ('delivery_timeline', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Delivery Execution Timeline')),
                ('advising_capability', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Vendor Advising Capability')),
                ('after_sales_qos', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='After Sales Services QOS')),
                ('vendor_relationship', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Note de 0 à 10', verbose_name='Vendor Relationship')),
                ('vendor_final_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moyenne des 5 critères (calculée automatiquement)', max_digits=4, verbose_name='Vendor Final Rating')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Évaluation fournisseur',
                'verbose_name_plural': 'Évaluations fournisseurs',
                'ordering': ['-date_evaluation'],
            },
        ),
    ]
