# Generated by Django 5.2.6 on 2025-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('capex', 'CAPEX'), ('opex', 'OPEX'), ('service', 'Service'), ('travaux', 'Travaux'), ('it', 'IT')], max_length=50)),
                ('type_contrat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de contrat')),
                ('type_activite', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'activité")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('XOF', 'XOF'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='XOF', max_length=10)),
                ('date_signature', models.DateField()),
                ('date_effet', models.DateField()),
                ('date_expiry', models.DateField()),
                ('preavis', models.IntegerField(default=90, help_text="Nombre de jours avant l'échéance")),
                ('duree_contrat', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Durée du contrat (années)')),
                ('type_renouvellement', models.CharField(blank=True, choices=[('tacite', 'Tacite'), ('accord_express', 'Par accord express'), ('avenant', 'Avenant')], max_length=20, null=True, verbose_name='Type de renouvellement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('expired', 'Expiré'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
