# Generated by Django 5.2.6 on 2025-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchasing_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchasing Group'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='release_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='release_indicator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Release indicator'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Order Unit'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='short_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short Text'),
        ),
    ]
