# Generated by Django 5.2.6 on 2025-11-13 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Photo de profil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('gestionnaire', 'Gestionnaire de projet'), ('collaborateur', 'Collaborateur')], default='collaborateur', max_length=20, verbose_name='Rôle')),
                ('direction', models.CharField(blank=True, help_text='Direction de rattachement (IT, Marketing, Finance, etc.)', max_length=100, verbose_name='Direction')),
                ('is_active', models.BooleanField(default=False, help_text='Indique si le compte est activé', verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('temporary_password', models.CharField(blank=True, help_text="Mot de passe temporaire haché pour l'activation", max_length=255, null=True, verbose_name='Mot de passe temporaire (haché)')),
                ('activation_token', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="Token d'activation")),
                ('token_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de création du token')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
    ]
