# Generated by Django 5.2.6 on 2025-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet_organisation', models.CharField(max_length=255, verbose_name="Nom complet de l'organisation")),
                ('type_fournisseur', models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], max_length=10, verbose_name='Type (Local/Foreign)')),
                ('type_organisation', models.CharField(choices=[('SA', 'SA'), ('SARL', 'SARL')], max_length=50, verbose_name="Type d'organisation (SA,SARL,…..)")),
                ('date_enregistrement', models.DateField(verbose_name="Date d'enregistrement")),
                ('adresse_physique', models.TextField(verbose_name='Adresse physique complète')),
                ('adresse_siege_social', models.TextField(blank=True, null=True, verbose_name='Adresse du siège social (si différente)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse électronique')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web (si existant)')),
                ('nom_representant_legal', models.CharField(max_length=255, verbose_name='Nom du Représentant Légal')),
                ('fonction_representant', models.CharField(max_length=255, verbose_name='Fonction')),
                ('personne_contact', models.CharField(max_length=255, verbose_name='Personne de contact pour les demandes de renseignements')),
                ('telephone_contact', models.CharField(max_length=20, verbose_name='Phone')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('registre_commerce', models.CharField(max_length=255, verbose_name='Registre de Commerce')),
                ('numero_compte_contribuable', models.CharField(max_length=255, verbose_name='Numéro compte contribuable')),
                ('attestation_regularite_fiscale', models.CharField(max_length=255, verbose_name='Attestation de régularité fiscale')),
                ('numero_cnps', models.CharField(max_length=255, verbose_name='Numéro CNPS')),
                ('banque', models.CharField(max_length=255, verbose_name='Banque')),
                ('agence', models.CharField(max_length=255, verbose_name='Agence')),
                ('iban', models.CharField(max_length=24, verbose_name='IBAN (24 positions pour les Locaux)')),
                ('bic_swift', models.CharField(blank=True, max_length=11, null=True, verbose_name='BICCODE/SWIFT (mandatory for Foreign Suppliers)')),
                ('modalite_paiement', models.CharField(choices=[('Net 30', 'Net 30'), ('Net 60', 'Net 60'), ('Net 90', 'Net 90')], max_length=10, verbose_name='Modalité de règlement')),
                ('type_categorie', models.CharField(choices=[('Biens', 'Biens'), ('Services', 'Services'), ('Autres', 'Autres')], max_length=20, verbose_name='Type Catégorie (Biens,Services, Autres…)')),
                ('categorie', models.CharField(choices=[('Fournitures générales de bureau et papeterie', 'Fournitures générales de bureau et papeterie'), ('Fourniture générale de matériel promotionnel', 'Fourniture générale de matériel promotionnel'), ("Fourniture générale de matériel d'entretien", "Fourniture générale de matériel d'entretien"), ('Fourniture de boissons et de snacks', 'Fourniture de boissons et de snacks'), ('Fournitures médicales et consommables', 'Fournitures médicales et consommables'), ('Appareils informatiques', 'Appareils informatiques')], max_length=255, verbose_name='Catégorie')),
                ('description_categorie', models.TextField(verbose_name='Description Catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom_complet_organisation'],
            },
        ),
    ]
