# Generated by Django 5.2.6 on 2025-11-18 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de bon de commande')),
                ('_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Montant total (cache)')),
                ('_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Montant reçu (cache)')),
                ('_remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Montant restant (cache)')),
                ('_progress_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Taux d'avancement (%) (cache)")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/imports/', verbose_name='Fichier importé')),
                ('extension', models.CharField(editable=False, max_length=10, verbose_name='Extension')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name="Date d'import")),
                ('rows_count', models.IntegerField(default=0, editable=False, verbose_name='Nombre de lignes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Fichier importé',
                'verbose_name_plural': 'Fichiers importés',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=255, unique=True, verbose_name='ID métier (PO + Item)')),
                ('purchasing_document', models.CharField(max_length=100, verbose_name='Purchasing Document')),
                ('item', models.CharField(max_length=50, verbose_name='Item')),
                ('net_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Net Order Value')),
                ('order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Order Quantity')),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Net Price')),
                ('received_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Received Quantity')),
                ('still_to_be_delivered_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Still to be delivered (qty)')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.purchaseorder', verbose_name='Bon de commande')),
            ],
            options={
                'verbose_name': 'Ligne de bon de commande',
                'verbose_name_plural': 'Lignes de bon de commande',
                'ordering': ['purchasing_document', 'item'],
            },
        ),
    ]
