# Generated by Django 5.2.6 on 2025-12-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_nom_complet_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la banque')),
                ('sigle', models.CharField(max_length=50, verbose_name='Sigle')),
                ('code_banque', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code banque (5 chiffres)')),
                ('code_bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='Code BIC/SWIFT')),
                ('iban_prefix', models.CharField(default='CI93', max_length=4, verbose_name='Préfixe IBAN')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse principale')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
            ],
            options={
                'verbose_name': 'Banque',
                'verbose_name_plural': 'Banques',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='banque',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banque (texte libre)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bic_swift',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BICCODE/SWIFT (obligatoire pour Foreign Suppliers)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='iban',
            field=models.CharField(max_length=28, verbose_name='IBAN (28 positions pour les Locaux)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_organisation',
            field=models.CharField(choices=[('SA', 'SA'), ('SARL', 'SARL'), ('SUARL', 'SUARL'), ('GIE', 'GIE'), ('SNC', 'SNC'), ('SCS', 'SCS'), ('SCA', 'SCA'), ('SCOP', 'SCOP'), ('Association', 'Association'), ('Autre', 'Autre')], max_length=50, verbose_name="Type d'organisation"),
        ),
        migrations.AddField(
            model_name='supplier',
            name='banque_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.banque', verbose_name='Banque (référence)'),
        ),
    ]
